# Filebeat configuration for DDV system

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/ddv/*.log
    fields:
      service: ddv
      environment: production
    fields_under_root: true
    multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    multiline.negate: true
    multiline.match: after
    processors:
      - add_host_metadata:
          when.not.contains.tags: forwarded
      - add_docker_metadata: ~
      - add_kubernetes_metadata: ~

  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata: ~
      - add_kubernetes_metadata: ~

  - type: docker
    enabled: true
    containers.ids:
      - '*'
    containers.stream: all
    containers.path: '/var/lib/docker/containers'
    processors:
      - add_docker_metadata: ~
      - add_kubernetes_metadata: ~

  - type: kubernetes
    enabled: true
    in_cluster: true
    processors:
      - add_kubernetes_metadata: ~

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - drop_event:
      when:
        equals:
          message: ""

output.logstash:
  hosts: ["logstash:5044"]
  compression_level: 3
  bulk_max_size: 1024
  timeout: 30s

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "ddv-logs-%{+yyyy.MM.dd}"
  template.name: "ddv-logs"
  template.pattern: "ddv-logs-*"
  template.settings:
    index.number_of_shards: 1
    index.number_of_replicas: 1
    index.lifecycle.name: "ddv-logs-policy"
    index.lifecycle.rollover_alias: "ddv-logs"
  ilm.enabled: true
  ilm.rollover_alias: "ddv-logs"
  ilm.pattern: "000001"
  ilm.policy: "ddv-logs-policy"

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 1
  index.lifecycle.name: "ddv-logs-policy"
  index.lifecycle.rollover_alias: "ddv-logs"

setup.ilm.enabled: true
setup.ilm.rollover_alias: "ddv-logs"
setup.ilm.pattern: "000001"
setup.ilm.policy: "ddv-logs-policy"

setup.kibana:
  host: "kibana:5601"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]

http.enabled: true
http.host: "0.0.0.0"
http.port: 5066

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]
