# Elasticsearch configuration for DDV system

cluster.name: ddv-cluster
node.name: ddv-node-1
node.roles: [ master, data, ingest ]

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery settings
discovery.seed_hosts: ["elasticsearch:9300"]
cluster.initial_master_nodes: ["ddv-node-1"]

# Memory settings
bootstrap.memory_lock: true

# Security settings (for development)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Index settings
action.auto_create_index: true
action.destructive_requires_name: true

# Logging settings
logger.level: INFO
logger.org.elasticsearch.transport: WARN
logger.org.elasticsearch.discovery: WARN

# Performance settings
indices.memory.index_buffer_size: 20%
indices.queries.cache.size: 10%
indices.fielddata.cache.size: 20%

# Thread pool settings
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000

# Circuit breaker settings
indices.breaker.total.limit: 70%
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 60%

# Cluster settings
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95%

# Index lifecycle management
xpack.ilm.enabled: true

# Monitoring settings
xpack.monitoring.collection.enabled: true
xpack.monitoring.exporters.logstash:
  type: logstash
  hosts: ["logstash:5044"]

# Machine learning settings
xpack.ml.enabled: true

# Watcher settings
xpack.watcher.enabled: true

# Cross-cluster replication
xpack.ccr.enabled: true

# Snapshot and restore
path.repo: ["/usr/share/elasticsearch/backups"]

# Custom settings for DDV
cluster.max_shards_per_node: 1000
indices.recovery.max_bytes_per_sec: 100mb
indices.store.preload: ["nvd", "dvd", "tim", "doc", "dim"]

# JVM heap settings (set via environment variables)
# ES_JAVA_OPTS: "-Xms2g -Xmx2g"

# Logging configuration
log4j2.properties: |
  status = error
  appender.console.type = Console
  appender.console.name = console
  appender.console.layout.type = PatternLayout
  appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %.-10000m%n

  appender.rolling.type = RollingFile
  appender.rolling.name = rolling
  appender.rolling.fileName = ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}.log
  appender.rolling.layout.type = PatternLayout
  appender.rolling.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %.-10000m%n
  appender.rolling.filePattern = ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}-%i.log.gz
  appender.rolling.policies.type = Policies
  appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
  appender.rolling.policies.size.size = 128MB
  appender.rolling.strategy.type = DefaultRolloverStrategy
  appender.rolling.strategy.fileIndex = nomax
  appender.rolling.strategy.action.type = Delete
  appender.rolling.strategy.action.basepath = ${sys:es.logs.base_path}
  appender.rolling.strategy.action.condition.type = IfFileName
  appender.rolling.strategy.action.condition.glob = ${sys:es.logs.cluster_name}-*
  appender.rolling.strategy.action.condition.nested_condition.type = IfAccumulatedFileSize
  appender.rolling.strategy.action.condition.nested_condition.exceeds = 2GB

  rootLogger.level = info
  rootLogger.appenderRef.console.ref = console
  rootLogger.appenderRef.rolling.ref = rolling

  logger.deprecation.name = org.elasticsearch.deprecation
  logger.deprecation.level = deprecation
  logger.deprecation.appenderRef.rolling.ref = rolling
  logger.deprecation.additivity = false

  logger.audit.name = org.elasticsearch.xpack.security.audit
  logger.audit.level = info
  logger.audit.appenderRef.rolling.ref = rolling
  logger.audit.additivity = false

  logger.index_search_slowlog_rolling.type = RollingFile
  logger.index_search_slowlog_rolling.name = index_search_slowlog_rolling
  logger.index_search_slowlog_rolling.fileName = ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_index_search_slowlog.log
  logger.index_search_slowlog_rolling.layout.type = PatternLayout
  logger.index_search_slowlog_rolling.layout.pattern = [%d{ISO8601}][%-5p][%-25c] [%node_name]%marker %.-10000m%n
  logger.index_search_slowlog_rolling.filePattern = ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_index_search_slowlog-%i.log.gz
  logger.index_search_slowlog_rolling.policies.type = Policies
  logger.index_search_slowlog_rolling.policies.size.type = SizeBasedTriggeringPolicy
  logger.index_search_slowlog_rolling.policies.size.size = 128MB
  logger.index_search_slowlog_rolling.strategy.type = DefaultRolloverStrategy
  logger.index_search_slowlog_rolling.strategy.fileIndex = nomax
  logger.index_search_slowlog_rolling.strategy.action.type = Delete
  logger.index_search_slowlog_rolling.strategy.action.basepath = ${sys:es.logs.base_path}
  logger.index_search_slowlog_rolling.strategy.action.condition.type = IfFileName
  logger.index_search_slowlog_rolling.strategy.action.condition.glob = ${sys:es.logs.cluster_name}_index_search_slowlog-*
  logger.index_search_slowlog_rolling.strategy.action.condition.nested_condition.type = IfAccumulatedFileSize
  logger.index_search_slowlog_rolling.strategy.action.condition.nested_condition.exceeds = 2GB

  logger.index_indexing_slowlog_rolling.type = RollingFile
  logger.index_indexing_slowlog_rolling.name = index_indexing_slowlog_rolling
  logger.index_indexing_slowlog_rolling.fileName = ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_index_indexing_slowlog.log
  logger.index_indexing_slowlog_rolling.layout.type = PatternLayout
  logger.index_indexing_slowlog_rolling.layout.pattern = [%d{ISO8601}][%-5p][%-25c] [%node_name]%marker %.-10000m%n
  logger.index_indexing_slowlog_rolling.filePattern = ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_index_indexing_slowlog-%i.log.gz
  logger.index_indexing_slowlog_rolling.policies.type = Policies
  logger.index_indexing_slowlog_rolling.policies.size.type = SizeBasedTriggeringPolicy
  logger.index_indexing_slowlog_rolling.policies.size.size = 128MB
  logger.index_indexing_slowlog_rolling.strategy.type = DefaultRolloverStrategy
  logger.index_indexing_slowlog_rolling.strategy.fileIndex = nomax
  logger.index_indexing_slowlog_rolling.strategy.action.type = Delete
  logger.index_indexing_slowlog_rolling.strategy.action.basepath = ${sys:es.logs.base_path}
  logger.index_indexing_slowlog_rolling.strategy.action.condition.type = IfFileName
  logger.index_indexing_slowlog_rolling.strategy.action.condition.glob = ${sys:es.logs.cluster_name}_index_indexing_slowlog-*
  logger.index_indexing_slowlog_rolling.strategy.action.condition.nested_condition.type = IfAccumulatedFileSize
  logger.index_indexing_slowlog_rolling.strategy.action.condition.nested_condition.exceeds = 2GB

  logger.index_search_slowlog.level = trace
  logger.index_search_slowlog.appenderRef.index_search_slowlog_rolling.ref = index_search_slowlog_rolling
  logger.index_search_slowlog.additivity = false

  logger.index_indexing_slowlog.level = trace
  logger.index_indexing_slowlog.appenderRef.index_indexing_slowlog_rolling.ref = index_indexing_slowlog_rolling
  logger.index_indexing_slowlog.additivity = false
